name: "Gray Area Creative Code Summer Immersive (2014)"
baseurl: "http://grayareaorg.github.io/Summer-Immersive-2014/"
description: ""
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
